backend:
  name: git-gateway
  branch: master 
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections: 
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date as dd/mm/yy", name: "day", widget: "string" }
      - { label: "Short Description", name: "descriptionShort", widget: "string" }
      - { label: "Large Description", name: "descriptionLarge", widget: "string" }
      - { label: "Choose Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      